### ISSUE TITLE
PCCP 모의고사_1

### ISSUE THREAD

**Issue by su8y** [su8y/PS-ATTACK#53]
[PCCP모의고사_1](https://school.programmers.co.kr/learn/courses/15008/15008-pccp-%EB%AA%A8%EC%9D%98%EA%B3%A0%EC%82%AC-1%ED%9A%8C)

**Comment by su8y** [comment]
@tecte1023 Come Come

**Comment by su8y** [comment]
4시간 3문제

**Comment by tecte1023** [comment]
4문제 5시간
